### ISSUE TITLE
Providing manual report

### ISSUE THREAD

**Issue by limx198918** [sofastack/sofa-tracer#81]
It provides manual reporting of data to Zipkin, for example, what does a timer need to report data?

**Comment by guanchao-yang** [comment]
@limx198918 You want to self define the span to be reported and show in Zipkin.We will support it.

**Comment by limx198918** [comment]
What is the time plan and what version will support it?

**Comment by guanchao-yang** [comment]
@limx198918 sorry, we will support it in version `3.1.0`

**Comment by glmapper** [comment]
@limx198918 @guanchao-yang 

The manual report method is already in the works, I am sorry that we may not be available in the v3.x version.The reason is [here](https://github.com/alipay/sofa-tracer/milestone/12).Considering the refactoring effect of the buried point approach, we will provide this feature in version 4.0.0.
